export declare class VerifyParam {
    private parameterSrv;
    private param;
    private paramName;
    private paramSet;
    private validationErrorMsg;
    constructor(parameter: any, parameterName?: string);
    private paramIsSet();
    private setError(msg);
    isDefined(): void;
    isDefinedOrThrowError(err?: any): void;
    isNotDefined(): void;
    isSet(): void;
    isSetOrThrowError(err?: any): void;
    isSetOrUseDefault(): void;
    isNotSet(): void;
    isTruthy(): void;
    isFalsey(): void;
    isValid(): boolean;
    isNotValid(): boolean;
    isValidOrThrowError(err?: any): boolean;
    string(): VerifyParam;
    array(): void;
    number(allowNumbersAsStrings?: boolean): VerifyParam;
    int(): void;
    json(): void;
    min(): void;
    max(): void;
    email(): void;
    equals(val: any): void;
    notEquals(val: any): void;
    lengthEquals(val: number): void;
    empty(): void;
    notEmpty(): void;
}
