export declare class VerifyParam {
    private parameterSrv;
    private equalSrv;
    private param;
    private paramName;
    private paramSet;
    private validationErrorMsg;
    constructor(parameter: any, parameterName?: string);
    private paramIsSet();
    private setError(msg);
    isDefined(): boolean;
    isDefinedOrThrowError(err?: any): boolean;
    isNotDefined(): boolean;
    isSet(): boolean;
    isNotSet(): boolean;
    isSetOrThrowError(err?: any): boolean;
    isSetOrUseDefault(defaultVal: any): any;
    isTruthy(): boolean;
    isFalsey(): boolean;
    isValid(): boolean;
    isNotValid(): boolean;
    isValidOrThrowError(err?: any): boolean;
    string(): VerifyParam;
    array(): VerifyParam;
    number(allowNumberAsString?: boolean): VerifyParam;
    int(allowIntAsString?: boolean): VerifyParam;
    json(): VerifyParam;
    email(): VerifyParam;
    min(val: number): VerifyParam;
    max(): void;
    equals(val: any): void;
    notEquals(val: any): void;
    lengthEquals(val: number): void;
    empty(): void;
    notEmpty(): void;
}
